# Generated by Django 6.0 on 2025-12-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='social_media',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
